env:
  test
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
  instance:
    hostname: sellorder
    prefer-ip-address: true
logging:
  pattern:
    console: "%d - %msg%n"
  file: D:\Program Files\Tomcat\log\sell_order
server:
#  port: 8080
  servlet:
   context-path: /sellorder
  tomcat:
    uri-encoding: UTF-8

spring:
  servlet:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.110/wds_order?characterEncoding=utf-8&useSSL=false
  freemarker:
    cache: false
    content-type: text/html
    template-loader-path: classpath:/templates
    enabled: true
    charset: utf-8
    suffix: .ftl
  mvc:
    static-path-pattern: /**
  redis:
    host: 192.168.0.110
    port: 6379
  application:
    name: sellorder

project-url:
  game: http://localhost:8080

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000
  index_test_key:
    execution:
      isolation:
        thread:
          timeoutInMilliseconds: 5000
userparameter:
  name: wushuailong
  age: 30
